### ISSUE TITLE
Error on first start

### ISSUE THREAD

**Issue by clemone210** [DanielNery/odoo-docker-compose-nginx-postgresql#3]
Dear,

I get following error on first run:

```
Starting nginx      ... done
Starting postgresql ... done
Creating odoo_odoo_run ... done
2023-03-17 08:26:12,656 1 WARNING ? py.warnings: /usr/lib/python3/dist-packages/odoo/tools/config.py:559: DeprecationWarning: The osv-memory-age-limit is a deprecated alias to the transient-age-limit option, please use the latter.
  File "/usr/bin/odoo", line 8, in <module>
    odoo.cli.main()
  File "/usr/lib/python3/dist-packages/odoo/cli/command.py", line 56, in main
    o.run(args)
  File "/usr/lib/python3/dist-packages/odoo/cli/server.py", line 179, in run
    main(args)
  File "/usr/lib/python3/dist-packages/odoo/cli/server.py", line 127, in main
    odoo.tools.config.parse_config(args)
  File "/usr/lib/python3/dist-packages/odoo/tools/config.py", line 378, in parse_config
    self._warn_deprecated_options()
  File "/usr/lib/python3/dist-packages/odoo/tools/config.py", line 559, in _warn_deprecated_options
    warnings.warn(
 
2023-03-17 08:26:12,657 1 WARNING ? py.warnings: /usr/lib/python3/dist-packages/odoo/tools/config.py:565: DeprecationWarning: The longpolling-port is a deprecated alias to the gevent-port option, please use the latter.
  File "/usr/bin/odoo", line 8, in <module>
    odoo.cli.main()
  File "/usr/lib/python3/dist-packages/odoo/cli/command.py", line 56, in main
    o.run(args)
  File "/usr/lib/python3/dist-packages/odoo/cli/server.py", line 179, in run
    main(args)
  File "/usr/lib/python3/dist-packages/odoo/cli/server.py", line 127, in main
    odoo.tools.config.parse_config(args)
  File "/usr/lib/python3/dist-packages/odoo/tools/config.py", line 378, in parse_config
    self._warn_deprecated_options()
  File "/usr/lib/python3/dist-packages/odoo/tools/config.py", line 565, in _warn_deprecated_options
    warnings.warn(
 
2023-03-17 08:26:12,657 1 INFO ? odoo: Odoo version 16.0-20230310 
2023-03-17 08:26:12,657 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf 
2023-03-17 08:26:12,657 1 INFO ? odoo: addons paths: ['/usr/lib/python3/dist-packages/odoo/addons', '/mnt/extra-addons'] 
2023-03-17 08:26:12,657 1 INFO ? odoo: database: odoo@db:5432 
2023-03-17 08:26:12,778 1 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2023-03-17 08:26:12,970 1 INFO ? odoo.modules.loading: init db 
2023-03-17 08:26:14,422 1 INFO your_database odoo.modules.loading: loading 1 modules... 
2023-03-17 08:26:14,423 1 INFO your_database odoo.modules.loading: Loading module base (1/1) 
2023-03-17 08:26:14,465 1 INFO your_database odoo.modules.registry: module base: creating or updating database tables 
2023-03-17 08:26:14,821 1 INFO your_database odoo.models: Prepare computation of ir.module.module.menus_by_module 
2023-03-17 08:26:14,821 1 INFO your_database odoo.models: Prepare computation of ir.module.module.reports_by_module 
2023-03-17 08:26:14,821 1 INFO your_database odoo.models: Prepare computation of ir.module.module.views_by_module 
2023-03-17 08:26:14,931 1 INFO your_database odoo.models: Prepare computation of res.partner.user_id 
2023-03-17 08:26:14,931 1 INFO your_database odoo.models: Prepare computation of res.partner.commercial_partner_id 
2023-03-17 08:26:14,931 1 INFO your_database odoo.models: Prepare computation of res.partner.display_name 
2023-03-17 08:26:14,931 1 INFO your_database odoo.models: Prepare computation of res.partner.company_registry 
2023-03-17 08:26:14,932 1 INFO your_database odoo.models: Prepare computation of res.partner.commercial_company_name 
2023-03-17 08:26:14,932 1 INFO your_database odoo.models: Prepare computation of res.partner.partner_share 
2023-03-17 08:26:14,973 1 INFO your_database odoo.models: Prepare computation of res.currency.decimal_places 
2023-03-17 08:26:15,002 1 INFO your_database odoo.models: Prepare computation of res.company.logo_web 
2023-03-17 08:26:15,031 1 INFO your_database odoo.models: Prepare computation of res.users.signature 
2023-03-17 08:26:15,031 1 INFO your_database odoo.models: Prepare computation of res.users.share 
2023-03-17 08:26:16,474 1 INFO your_database odoo.modules.loading: loading base/data/res_bank.xml 
2023-03-17 08:26:16,480 1 INFO your_database odoo.modules.loading: loading base/data/res.lang.csv 
2023-03-17 08:26:16,586 1 INFO your_database odoo.modules.loading: loading base/data/res_lang_data.xml 
2023-03-17 08:26:16,645 1 ERROR your_database odoo.sql_db: bad query: UPDATE ir_module_module SET state='installed' WHERE state IN ('to remove', 'to upgrade')
ERROR: relation "ir_module_module" does not exist
LINE 1: UPDATE ir_module_module SET state='installed' WHERE state IN...
               ^
 
2023-03-17 08:26:16,646 1 ERROR your_database odoo.modules.registry: Failed to load registry 
2023-03-17 08:26:16,646 1 CRITICAL your_database odoo.service.server: Failed to initialize database `your_database`. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 698, in _tag_root
    f(rec)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 599, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4349, in _load_records
    data['record']._load_records_write(data['values'])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4280, in _load_records_write
    self.write(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_lang.py", line 308, in write
    res = super(Lang, self).write(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3735, in write
    field.write(self, value)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2475, in write
    super(Image, self).write(records, new_value)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2414, in write
    atts.create([{
  File "<decorator-gen-57>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 654, in create
    values.update(self._get_datas_related_values(
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 267, in _get_datas_related_values
    values['store_fname'] = self._file_write(data, values['checksum'])
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 128, in _file_write
    fname, full_path = self._get_path(bin_value, checksum)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 110, in _get_path
    os.makedirs(dirname)
  File "/usr/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/lib/odoo/filestore'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 428, in load_modules
    loaded_modules, processed_modules = load_module_graph(
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 230, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 763, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 829, in convert_xml_import
    obj.parse(doc.getroot())
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 749, in parse
    self._tag_root(de)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 698, in _tag_root
    f(rec)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 711, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing /usr/lib/python3/dist-packages/odoo/addons/base/data/res_lang_data.xml:10, somewhere inside
<record id="base.lang_ar" model="res.lang">
            <field name="flag_image" type="base64" file="base/static/img/lang_flags/lang_ar.png"/>
        </record>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 1299, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-14>", line 2, in new
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 92, in new
    odoo.modules.reset_modules_state(db_name)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 633, in reset_modules_state
    cr.execute(
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 313, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UndefinedTable: relation "ir_module_module" does not exist
LINE 1: UPDATE ir_module_module SET state='installed' WHERE state IN...
               ^

2023-03-17 08:26:16,654 1 INFO your_database odoo.service.server: Initiating shutdown 
2023-03-17 08:26:16,654 1 INFO your_database odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2023-03-17 08:26:16,654 1 INFO your_database odoo.sql_db: ConnectionPool(used=0/count=0/max=9): Closed 1 connections  
ERROR: 255
```

**Comment by DanielNery** [comment]
Hi, @clemone210 

This error is caused because your odoo-web-data volume does not have the necessary permissions. You can resolve using the following command in linux inside your project:

sudo chmod 777 odoo-web-data
sudo chmod 777 odoo-web-data/*
sudo chmod -R 777 odoo-web-data

**Comment by clemone210** [comment]
okay that resolved the issue.
When I run the project, everything is already setup.
Whats the default credentials?
